### ISSUE TITLE
请教语音转文字的方法

### ISSUE THREAD

**Issue by teetyler** [salvatore-w/flipradio.archive#1]
作者，你好。看到你贡献的flipradio文字稿非常开心。
想请教你是如何语音转文字的。如果可以，我也想贡献我的一份力量pull request，共同推进这个项目。

**Comment by salvatore-w** [comment]
谢谢你的支持。
如果你是讯飞听见的新用户，可以获得四个小时的转写试用时长（2 小时充值卡 + 2 小时优惠券）
然后申请讯飞的语音转写 API 也会赠送有 5 小时的时长，不过需要一点编程基础，我是按它文档里的示例稍微修改了一下就能用
以上两种免费的方式我全用完了，现在我是直接买的讯飞语音转写 API 时长，比讯飞听见便宜很多。
