### ISSUE TITLE
【转写认领】补足 2.0 第一章缺失部分

### ISSUE THREAD

**Issue by salvatore-w** [salvatore-w/flipradio.archive#12]
想要认领的节目标题（可使用 Markdown 列表认领多个）：
- [ ] 从客观到主观到中道（我们与概念的距离 2/2）纯粹理性批判

预计完成时间：2024 年前

补足 2.0 第一章缺失部分

**Comment by nukacoffee** [comment]
我来补上，下周起会有空。
- 从客观到主观到中道（我们与概念的距离 2/2）纯粹理性批判

**Comment by salvatore-w** [comment]
不是啊，认领是说我已经在做了

**Comment by nukacoffee** [comment]
哦哦😲那麻烦你了
