### ISSUE TITLE
【项目问题/建议】【讲义..】换行

### ISSUE THREAD

**Issue by MahjongKing96** [salvatore-w/flipradio.archive#26]
请描述你遇到的问题：

你对本项目的建议：【讲义..】标识可以单独起一行。增加可读性，快速翻阅时更显眼，也不影响正则匹配式或者未来其他处理脚本的运行。

**Comment by salvatore-w** [comment]
暂时不予考虑，原因如下：

1. 单独起一行之后是下面直接接内容还是空一行再接内容，甚至可能会有加粗，这些虽然不影响阅读，但到后面每个人会有不同习惯，这边也不好直接规范。
2. 我更倾向于认为讲义提示是“序号”而不是“标题”，就像 Markdown 的有序列表，这样更加强调内容的整体性。
3. 在一些可能出现段落顺序错误需要调整的极端情况下，可能会出现忘记复制讲义提示行的情况，导致顺序错乱

**Comment by MahjongKing96** [comment]
理解了。
