### ISSUE TITLE
关于直角引号的使用

### ISSUE THREAD

**Issue by nukacoffee** [salvatore-w/flipradio.archive#9]
这次的更新把所有的引号都撤换为直角引号，这一点我不同意。在文段中大量使用直角引号不符合大陆读者的阅读习惯。对此大家的意见是？

**Comment by salvatore-w** [comment]
1. 弯引号因为系统字体原因容易出现打反的状况，现在的「世界苦茶」 newsletter 会经常出现这种问题。
2. 弯引号又分全角和半角，因为输入法的不同容易显示错误，而且由于弯引号只有半个汉字宽度，现在也有观点认为需要在弯引号前后加半角空格，但这样规范起来更麻烦，更别提各种复杂的引号形式了（见：https://sspai.com/post/45516 ）
3. 就我个人观点而言，弯引号是和中西文字符之间插入空格一样需要在中文排版中普及，中文是方块字，直角引号会使排版显得更为整齐好看。（见：https://www.bilibili.com/video/av344003611 ）
4. 至于你提到的阅读习惯，我认为这并不是很难接受的事情，现在很多自媒体都在使用直角引号，使用直角引号排版并不鲜见，也就不存在不适应。
